export const SEARCH_TEXT = 'SEARCH_TEXT';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_LOGOUT = 'LOGIN_USER_LOGOUT';
export const RECEIVE_CHARGES_DATA = 'RECEIVE_CHARGES_DATA';
export const RECEIVE_HISTORY_DATA = 'RECEIVE_HISTORY_DATA';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const RECEIVE_NEWCHARGE_LIST = 'RECEIVE_NEWCHARGE_LIST';
export const CLOSE_POPUP = 'CLOSE_POPUP';
export const REMOVE_CHARGE_ROW = 'REMOVE_CHARGE_ROW';

export const CHARGE_REQUEST = 'CHARGE_REQUEST';
export const CHARGE_SUCCESS = 'CHARGE_SUCCESS';
